project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Ciência aberta e em colaboração"
  description: "Página da disciplina Ciência aberta e em colaboração do PPGA-CEFET-MG - 2023/2"
  site-url: "https://open-reproducible-research.github.io/website/"

  # twitter-card:
  #   creator: "@retaoliveira"
  #   image: "images/twitter-card.png"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/), based on the template of Mine Çetinkaya-Rundel."
    left: "License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    # background: "#45818E"

  sidebar:
    # background: "#45818E"
    #logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/open-reproducible-research
        text: "GitHub organization"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Informações gerais sobre o curso"
        contents:
          - href: programa.qmd
            text: Planejamento do curso
          - href: links.qmd
            text: Links
          - href: suporte.qmd
            text: Suporte
      - section: "Material semanal"
        contents:
          - href: weeks/week-1.qmd
            text: "Semana 1"
          # - href: weeks/week-2.qmd
          #   text: "Semana 2"
          # - href: weeks/week-3.qmd
          #   text: "Semana 3"
          # - href: weeks/week-4.qmd
          #   text: "Semana 4"
          # - href: weeks/week-5.qmd
          #   text: "Semana 5"
          # - href: weeks/week-6.qmd
          #   text: "Semana 6"
          # - href: weeks/week-7.qmd
          #   text: "Semana 7"
          # - href: weeks/week-8.qmd
          #   text: "Semana 8"
          # - href: weeks/week-9.qmd
          #   text: "Week 9"
          # - href: weeks/week-10.qmd
          #   text: "Week 10"
          # - href: weeks/week-11.qmd
          #   text: "Week 11"
          # - href: weeks/week-12.qmd
          #   text: "Week 12"
          # - href: weeks/week-13.qmd
          #   text: "Week 13"
          # - href: weeks/week-14.qmd
          #   text: "Week 14"
          # - href: weeks/week-15.qmd
          #   text: "Week 15"
      # - section: "Project"
      #   contents:
      #     - href: project-description.qmd
      #       text: Description
      #     - href: project-tips-resources.qmd
      #       text: Tips + resources
#      - section: "Informações suplementares"
#        contents:
#          - href: supplemental/slr-derivations.qmd
#            text: SLR derivations
#          - href: supplemental/model-diagnostics-matrix.qmd
#            text: Model diagnostics
#          - href: supplemental/mlr-matrix.qmd
#            text: MLR matrix notation
#          - href: supplemental/log-transformations.qmd
#            text: Log transformations
#          - href: supplemental/model-selection-criteria.qmd
#            text: Model selection criteria

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual